---

# Create AH EE registry
- name: Index Automation Hub EE Registry
  ah_ee_registry_index:
    name:                   "{{ __ee_registry_item.name }}"
    wait:                   "{{ __ee_registry_item.wait | default(omit) }}"
    interval:               "{{ __ee_registry_item.interval | default(omit) }}"
    timeout:                "{{ __ee_registry_item.timeout | default(omit) }}"
    ah_host:                "{{ ah_host | default(ah_hostname) }}"
    ah_username:            "{{ ah_username | default(omit) }}"
    ah_password:            "{{ ah_password | default(omit) }}"
    ah_path_prefix:         "{{ ah_path_prefix | default(omit) }}"
    validate_certs:         "{{ ah_validate_certs | default(omit) }}"
  loop: "{{ ah_ee_registries }}"
  loop_control:
    loop_var: "__ee_registry_item"
  no_log: "{{ ah_configuration_ee_registry_secure_logging }}"
...
