---

# Create AH EE Image
- name: Add Automation Hub EE Image
  ah_ee_image:
    name:             "{{ __ee_image_item.name }}"
    # new_name:         "{{ __ee_image_item.new_name | default(omit) }}"  <-- Needs adding once new_name option added to module
    append: "{{ __ee_image_item.append | default(omit) }}"
    tags: "{{ __ee_image_item.tags | default(omit) }}"
    state:            "{{ __ee_image_item.state | default(ah_state | default('present')) }}"
    ah_host:          "{{ ah_hostname | default(ah_host) }}"
    ah_username:      "{{ ah_username | default(omit) }}"
    ah_password:      "{{ ah_password | default(omit) }}"
    ah_path_prefix:   "{{ ah_path_prefix | default(omit) }}"
    validate_certs:   "{{ ah_validate_certs | default(omit) }}"
  loop: "{{ ah_ee_images }}"
  loop_control:
    loop_var: "__ee_image_item"
  no_log: "{{ ah_configuration_ee_image_secure_logging }}"
...
