---
- name: Add ansible tower notifications
  awx.awx.tower_notification:
    channels:              "{{ tower_notifications_item.channels | default(omit) }}"
    description:           "{{ tower_notifications_item.description | default(omit) }}"
    host:                  "{{ tower_notifications_item.host | default(omit) }}"
    name:                  "{{ tower_notifications_item.name }}"
    nickname:              "{{ tower_notifications_item.nickname | default(omit) }}"
    notification_type:     "{{ tower_notifications_item.notification_type }}"
    organization:          "{{ tower_notifications_item.organization | default(omit) }}"
    username:              "{{ tower_notifications_item.username | default(omit) }}"
    password:              "{{ tower_notifications_item.password | default(omit) }}"
    port:                  "{{ tower_notifications_item.port | default(omit) }}"
    recipients:            "{{ tower_notifications_item.recipients | default(omit) }}"
    sender:                "{{ tower_notifications_item.sender| default(omit) }}"
    server:                "{{ tower_notifications_item.server| default(omit) }}"
    state:                 "{{ tower_notifications_item.state | default(tower_state | default('present')) }}"
    targets:               "{{ tower_notifications_item.targets | default(omit) }}"
    use_ssl:               "{{ tower_notifications_item.use_ssl | default('false') }}"
    use_tls:               "{{ tower_notifications_item.use_tls | default('false')   }}"
    tower_host:            "{{ tower_hostname }}"
    tower_username:        "{{ tower_username | default('admin') }}"
    tower_password:        "{{ tower_password }}"
    tower_verify_ssl:      "{{ tower_verify_ssl | default('false') }}"
  loop: "{{ tower_notifications }}"
  loop_control:
    loop_var: tower_notifications_item
  no_log: "{{ tower_configuration_notifications_secure_logging }}"
  when: tower_notifications is defined
