---
# tasks file for tower_settings

- name: Update Ansible Tower Settings
  awx.awx.tower_settings:
    settings:            "{{ tower_settings.settings | default(omit) }}"
    tower_config_file:   "{{ tower_config_file | default(omit) }}"
    tower_host:          "{{ tower_hostname | default(omit) }}"
    tower_password:      "{{ tower_password | default(omit) }}"
    tower_username:      "{{ tower_username | default(omit) }}"
    validate_certs:      "{{ validate_certs | default('false') }}"
  when: tower_settings.settings is defined
  no_log: "{{ tower_configuration_settings_secure_logging }}"

- debug:
    var: tower_settings[0]

- name: When tower settings is a list use the list.
  block:
    - name: Update Ansible Tower Settings as a List
      awx.awx.tower_settings:
        name:                "{{ tower_setting_item.name | default(omit) }}"
        value:               "{{ tower_setting_item.value | default(omit) }}"
        tower_config_file:   "{{ tower_config_file | default(omit) }}"
        tower_host:          "{{ tower_hostname | default(omit) }}"
        tower_password:      "{{ tower_password | default(omit) }}"
        tower_username:      "{{ tower_username | default(omit) }}"
        validate_certs:      "{{ validate_certs | default('false') }}"
      loop: "{{ tower_settings }}"
      loop_control:
        loop_var: tower_setting_item
      no_log: "{{ tower_configuration_settings_secure_logging }}"
  when: tower_settings[0] is defined
...
