---

# Create AH EE Namespace
- name: Add Automation Hub Execution Environment Namespace
  ah_ee_namespace:
    name:             "{{ __ee_namespace_item.name }}"
    # new_name:         "{{ __ee_namespace_item.new_name | default(omit) }}"  <-- Needs adding once new_name option added to module
    append:           "{{ __ee_namespace_item.append | default(omit) }}"
    groups:           "{{ __ee_namespace_item.groups | default([]) }}"
    state:            "{{ __ee_namespace_item.state | default(ah_state | default('present')) }}"
    ah_host:          "{{ ah_host | default(ah_hostname) }}"
    ah_username:      "{{ ah_username | default(omit) }}"
    ah_password:      "{{ ah_password | default(omit) }}"
    ah_path_prefix:   "{{ ah_path_prefix | default(omit) }}"
    validate_certs:   "{{ ah_validate_certs | default(omit) }}"
  loop: "{{ ah_ee_namespaces }}"
  loop_control:
    loop_var: "__ee_namespace_item"
  no_log: "{{ ah_configuration_ee_namespace_secure_logging }}"
...
