---
tower_hostname: ""
tower_oauthtoken: ""
tower_validate_certs: false
tower_configuration_credential_input_sources_secure_logging: "{{tower_configuration_secure_logging | default(false)}}"
tower_credential_input_sources:
  - source_credential: cyberark
    target_credential: gitlab
    input_field_name: password
    metadata:
      object_query: "Safe=MY_SAFE;Object=AWX-user"
      object_query_format: "Exact"
    description: Fill the gitlab credential from CyberArk
