---

# Create AH EE registry
- name: Add Automation Hub EE Registry
  ah_ee_registry:
    name:                   "{{ __ee_registry_item.name }}"
    new_name:               "{{ __ee_registry_item.new_name | default(omit) }}"
    url:                    "{{ __ee_registry_item.url }}"
    username:               "{{ __ee_registry_item.username | default(omit) }}"
    password:               "{{ __ee_registry_item.password | default(omit) }}"
    tls_validation:         "{{ __ee_registry_item.tls_validation | default(omit) }}"
    proxy_url:              "{{ __ee_registry_item.proxy_url | default(omit) }}"
    proxy_username:         "{{ __ee_registry_item.proxy_username | default(omit) }}"
    proxy_password:         "{{ __ee_registry_item.proxy_password | default(omit) }}"
    download_concurrency:   "{{ __ee_registry_item.download_concurrency | default(omit) }}"
    rate_limit:             "{{ __ee_registry_item.rate_limit | default(omit) }}"
    state:                  "{{ __ee_registry_item.state | default(ah_state | default('present')) }}"
    ah_host:                "{{ ah_host | default(ah_hostname) }}"
    ah_username:            "{{ ah_username | default(omit) }}"
    ah_password:            "{{ ah_password | default(omit) }}"
    ah_path_prefix:         "{{ ah_path_prefix | default(omit) }}"
    validate_certs:         "{{ ah_validate_certs | default(omit) }}"
  loop: "{{ ah_ee_registries }}"
  loop_control:
    loop_var: "__ee_registry_item"
  no_log: "{{ ah_configuration_ee_registry_secure_logging }}"
...
