---

# These are the default variables common to most tower_configuration and _utilities roles
# You shouldn't need to define them again and again but they should be defined
#tower_hostname: "{{ inventory_hostname }}"
#tower_username: "admin"
#tower_password: ""
#tower_oauthtoken: ""
#tower_config_file: ""
#tower_validate_certs: false

# These are the default variables specific to the users role

# list of dicts describing Tower users
tower_user_accounts: []
# possible fields:
#- username: "user_name"  # mandatory
#  password: "redhat"  # optional (write only, will mark task as changed)
#  email: "somebody@dev.null"  # optional
#  first_name: "Jim"  # optional
#  last_name: "Smith"  # optional
#  is_superuser: false  # optional, boolean
#  is_auditor: false  # optional, boolean
#  state: present  # optional, choices: present, absent

tower_configuration_users_secure_logging: "{{tower_configuration_secure_logging | default(false)}}"
