---
ah_configuration_dispatcher_roles:
  # - {role: ansible_config, var: ansible_config_list, tags: config}
  # - {role: ansible_config, var: automation_hub_list, tags: config}
  - {role: ansible_config, var: [ ansible_config_list, automation_hub_list], tags: config}
  - {role: collection, var: ah_collections, tags: collection}
  - {role: ee_image, var: ah_ee_images, tags: image}
  - {role: ee_namespace, var: ah_ee_namespaces, tags: namespace}
  - {role: ee_registry, var: ah_ee_registries, tags: registry}
  - {role: ee_registry_index, var: ah_ee_registries, tags: registry}
  - {role: ee_registry_sync, var: ah_ee_registries, tags: registry}
  - {role: ee_repository, var: ah_ee_repositories, tags: repository}
  - {role: ee_repository_sync, var: ee_repository_sync, tags: repository}
  - {role: group, var: ah_groups, tags: group}
  - {role: namespace, var: ah_namespaces, tags: namespace}
  - {role: publish, var: ah_collections, tags: collection}
  - {role: repository, var: ah_repository_certified|ah_repository_community, tags: repository}
  # - {role: repository, var: ah_repository_certified, tags: repository}
  # - {role: repository, var: ah_repository_community, tags: repository}
  - {role: repository_sync, var: repository_sync, tags: repository}
  - {role: user, var: ah_users, tags: user}
