---

# Create AH Group
- name: Add Automation Hub group
  ah_group:
    name:             "{{ __group.name | default(omit) }}"
    # new_name:         "{{ __group.new_name | default(omit) }}"  <-- Needs adding once new_name option added to module
    state:            "{{ __group.state | default(ah_state | default('present')) }}"
    ah_host:          "{{ ah_hostname | default(ah_host) }}"
    ah_username:      "{{ ah_username | default(omit) }}"
    ah_password:      "{{ ah_password | default(omit) }}"
    ah_path_prefix:   "{{ ah_path_prefix | default(omit) }}"
    validate_certs:   "{{ ah_validate_certs | default(omit) }}"
  loop: "{{ ah_groups }}"
  loop_control:
    loop_var: "__group"
  no_log: "{{ ah_configuration_group_secure_logging }}"

- name: Add Automation Hub group permissions
  ah_group_perm:
    name:             "{{ __group.new_name | default(__group.name | default(omit)) }}"
    perms:            "{{ __group.perms }}"
    state:            "{{ __group.state | default(ah_state | default('present')) }}"
    ah_host:          "{{ ah_hostname | default(ah_host) }}"
    ah_username:      "{{ ah_username | default(omit) }}"
    ah_password:      "{{ ah_password | default(omit) }}"
    ah_path_prefix:   "{{ ah_path_prefix | default(omit) }}"
    validate_certs:   "{{ ah_validate_certs | default(omit) }}"
  loop: "{{ ah_groups }}"
  loop_control:
    loop_var: "__group"
  when: __group.perms is defined
  no_log: "{{ ah_configuration_group_secure_logging }}"

...
